# Generated by Django 3.1.14 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20221007_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterField(
            model_name='report',
            name='ts',
            field=models.IntegerField(default=1665136100),
        ),
    ]
