# Generated by Django 3.1.14 on 2022-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20221007_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ts',
            field=models.IntegerField(default=1665389152),
        ),
    ]
