# Generated by Django 3.1.14 on 2022-10-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20221010_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=255)),
                ('ts', models.IntegerField(default=1665654573)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='ts',
            field=models.IntegerField(default=1665654573),
        ),
    ]
