# Generated by Django 3.1.14 on 2022-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20221013_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='raw',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ts',
            field=models.IntegerField(default=1665761576),
        ),
        migrations.AlterField(
            model_name='report',
            name='ts',
            field=models.IntegerField(default=1665761576),
        ),
    ]
